# Start from the alpine image that is smaller but no fancy tools
FROM ubuntu:24.04

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y curl unzip

# Install Deno for JavaScript runtime support
RUN curl -fsSL https://deno.land/install.sh | sh

# Add Deno to PATH
ENV PATH="/root/.deno/bin:${PATH}"

COPY script.sh .

RUN chmod +x script.sh

# When running docker run the command will be ./script.sh
ENTRYPOINT ["./script.sh"]